---
# tasks file for roles/elasticsearch
- name: include prepare_elasticsearch.yml
  include: prepare_elasticsearch.yml
- name: include install_elasticsearch.yml
  include: install_elasticsearch.yml
  tags:
    - install
- name: include configure_elasticsearch.yml
  include: configure_elasticsearch.yml
  tags:
    - configure
- name: include service_elasticsearch.yml
  include: service_elasticsearch.yml
  tags:
    - start
